import ChakraProvider from "@/app/components/chakra-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="en">
    <body>
      <ChakraProvider>{children}</ChakraProvider>
    </body>
  </html>
);

export default RootLayout;
